hillel_study/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from api.views import ProductViewSet
from core.views import (Index, ProductCreate, ProductCreateFinal, EditProductView, EditProduct, ProductList,
                        ProductListView, ProductDetail)
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('products', viewset=ProductViewSet)

urlpatterns = [
    path('backoffice/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
    # path('', Index.as_view())
    # path('', ProductCreate.as_view())
    path('', ProductListView.as_view(), name='index'),
    # path('edit/<int:id>/', EditProductView.as_view())
    path('edit/<int:id>/', EditProduct.as_view(), name='product_edit'),
    path('product/detail/<int:pk>/', ProductDetail.as_view(), name='product_detail')
] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

# /profile/1/
# /profile/2/
# ...
# /profile/404/

core/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser


class CreatedUpdated(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Brand(CreatedUpdated):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


# TODO: Bad practice!!!
# class SubBrand(Brand):
#     sub_name = models.CharField(max_length=255)

# TODO: Good practice!!!
# class SubBrand(CreatedUpdated):
#     name = models.CharField(max_length=255)
#     sub_name = models.CharField(max_length=255)

class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


# class TagProduct(models.Model):
#     product = models.ForeignKey('Product', on_delete=models.CASCADE)
#     tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
#     click_count = models.IntegerField()


class ProductManager(models.Manager):

    def get_good(self):
        return self.get_queryset().filter(condition=Product.CONDITION_GOOD)

    def get_by_condition(self, condition):
        return self.get_queryset().filter(condition=condition)

    # def get_queryset(self):
    #     queryset = super(ProductManager, self).get_queryset()
    #     return queryset.filter(is_deleted=False)


class Product(CreatedUpdated):
    #  core_product
    CONDITION_NEW = 1
    CONDITION_GOOD = 2
    CONDITION_NORMAL = 3
    CONDITION_OMFG = 4

    CONDITION_CHOICES = (
        (CONDITION_NEW, 'New car (less then month in use)'),
        (CONDITION_GOOD, 'Good car (less then year in use)'),
        (CONDITION_NORMAL, 'Normal car (less then 5 years in use)'),
        (CONDITION_OMFG, 'OMFG (peace of crap)')
    )

    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    run_km = models.IntegerField()
    condition = models.PositiveSmallIntegerField(choices=CONDITION_CHOICES)
    number_plate = models.CharField(max_length=8)
    tags = models.ManyToManyField(Tag, blank=True)  # through=TagProduct)
    is_deleted = models.BooleanField(default=False)

    objects = ProductManager()

    class Meta:
        # abstract = True
        db_table = 'product'
        ordering = ('id', 'created_at')
        unique_together = ('number_plate', 'brand')

    def __str__(self):
        return f"{self.number_plate}"

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        is_created = hasattr(self, 'pk')
        # pre_save
        super(Product, self).save(force_insert, force_update, using, update_fields)
        # post_save
        if is_created:
            # Code to send mail
            pass

#
# class MyAbstractController:
#
#     url_name = ...
#
#     def connection(self, ip, port):
#         raise NotImplemented
#
#
# class MyController(MyAbstractController):
#     pass
#


# @receiver(pre_save, sender=Product)
# def product_pre_save_action(sender, instance, **kwargs):
#     instance.run_km = 100


# class Profile(models.Model):
#     phone = models.CharField(max_length=11)
#     user = models.OneToOneField(User, on_delete=models.CASCADE)


class CustomUser(AbstractUser):
    phone = models.CharField(max_length=11)


@receiver(post_save, sender=Product)
def product_post_save_action(sender, instance, **kwargs):
    if kwargs['created']:
        # Code to send mail
        pass

templates/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block extra_header %} {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="/create_post/">Crate Post</a>
              </li>
            </ul>
              <ul class="navbar-nav mr-auto">
                  {% if user.is_authenticated %}
                      <li class="nav-item active">
                        <a class="nav-link" href="/accounts/logout/">Logout</a>
                      </li>
                  {% else %}
                      <li class="nav-item active">
                        <a class="nav-link" href="/accounts/login/">Login</a>
                      </li>
                  {% endif %}
              </ul>
          </div>
        </nav>
        <div class="container">
            {% block content %} {% endblock %}
        </div>

    </body>
</html>

templates/create_post_view.html
{% load bootstrap4 %}

<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="/create_post/">Crate Post</a>
              </li>
            </ul>
          </div>
        </nav>
        <div class="container">
            <form method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Create Post</button>
                {% endbuttons %}
            </form>
        </div>
    </body>
</html>

templates/edit_product.html
{% extends 'base.html' %}
{% load custom_filters custom_tags static %}

{% block extra_header %}
    <title>My Django site!</title>
    <link rel="stylesheet" href="{% static "css/main.css" %}">
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.errors }}
        <table>
            {{ form }}
            <tr>
                <td>
                    <button type="submit">Create</button>
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

templates/html_lesson.html
<html>
    <head>

        <style>
            /*p {
                color: red;
                background-color: #000000;
                font-size: 16px;
                font-weight: bold;
                /*width: 100px;
            }*/
            /*#id_text {
                color: green;
            }*/
            .super_text {
                color: red;
                font-weight: bold;
                font-size: 20px;
            }
            p.green, span.green {
                color: green;
            }
            li {
                list-style: none;
            }
        </style>
    </head>

    <body>
        <h1>Hello world</h1>
        <h2>Hello world</h2>
        <h3>Hello world</h3>
        <h4>Hello world</h4>

        <p class="super_text green" id="id_text">Lorem Ipsum is simply dummy text of the printing and
            typesetting industry. Lorem Ipsum has been the industry's
            standard dummy text ever since the 1500s, when an unknown
            printer took a galley of type and scrambled it to make a
            type specimen book. It has survived not only five centuries,
            but also the leap into electronic typesetting, remaining
            essentially unchanged. It was popularised in the 1960s
            with the release of Letraset sheets containing Lorem Ipsum
            passages, and more recently with desktop publishing software
            like Aldus PageMaker including versions of Lorem Ipsum.</p>

        <p>Lorem Ipsum is simply dummy text of the printing and
            typesetting industry. Lorem <b class="super_text green">Ipsum</b> has been the industry's
            standard dummy text ever since the 1500s, when an unknown
            printer took a <i>galley</i> of type and scrambled it to make a
            type specimen book. It has survived not only five centuries,
            but also the leap into electronic typesetting, <br> remaining
            essentially unchanged. It was popularised in the 1960s
            with the release of <span class="super_text green">Letraset</span> sheets containing Lorem Ipsum
            passages, and more recently with desktop publishing software
            like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <hr>
        <pre>
Help me!
Hello!                    Loki
        </pre>


    <table border="1" width="400px">
        <tr>
            <th>First</th>
            <th>Second</th>
            <th>Third</th>
        </tr>
        <tr>
            <td colspan="3">2</td>
        </tr>
        <tr>
            <td>1</td>
            <td>2</td>
            <td>3</td>
        </tr>
    </table>

    <ol>
        <li>First</li>
        <li>Second</li>
        <li>Third</li>
    </ol>

    <div>
        <p>qweqweqwe</p>
    </div>

    <form method="get" action="">
        <div>
            <input type="text" name="username">
        </div>

        <div>
            <input type="submit" value="Send">
            <button type="submit">Send</button>
        </div>
    </form>

    </body>
<script src="../static/js/main.js"></script>
</html>

templates/index.html
{% extends 'base.html' %}
{% load custom_filters custom_tags static %}

{% block extra_header %}
    <title>My Django site!</title>
    <link rel="stylesheet" href="{% static "css/main.css" %}">
{% endblock %}

{% block content %}
{#    <div class="row">#}
{#    {% if some_data %}#}
{#        <h1>{{ some_data }}</h1>#}
{#    {% else %}#}
{#        <h1>There is no data!</h1>#}
{#    {% endif %}#}
{##}
{#    <ul>#}
{#    {% with some=list_data.1 %}#}
{#        {% for name in list_data %}#}
{#            <li style="list-style: none">{{ forloop.last }}. {{ name|floatformat:2 }}</li>#}
{#        {% empty %}#}
{#            <h1>No data!</h1>#}
{#        {% endfor %}#}
{#    {% endwith %}#}
{#    </ul>#}
{##}
{#    {{ html_data|safe }}#}
{#    </div>#}
{#    <div class="col-12">#}
{#        {% lorem %}#}
{#    </div>#}
{##}
{#    {% verbatim %}#}
{#    <div class="col-12">#}
{#        {% lorem %}#}
{#    </div>#}
{#    {% endverbatim %}#}
{##}
{#    <h1>{{ 5|mutiply:5 }}</h1>#}
{#    <h1>{% discr 2 2 2 %}</h1>#}
{##}
{#    {% user_list %}#}

{#    {% include 'html_lesson.html' %}#}
{#    <h1>{{ all_run }}</h1>#}
{#    <ul>#}
{#    {% for product in products %}#}
{#        <li>#}
{#            {{ product.number_plate }} - {{ product.brand.name }} - {{ product.tags.all }}#}
{#        </li>#}
{#    {% endfor %}#}
{#    </ul>#}

{#    <ul>#}
{#        {% for brand in brands %}#}
{#        <li>#}
{#            {{ brand.name }} - Avg run {{ brand.avg_run|floatformat:0 }} - Products Count: {{ brand.product_count }}#}
{#        </li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#    <form method="post">{% csrf_token %}#}
{#        {{ form.errors }}#}
{#        <table>#}
{#            <tr>#}
{#                <td>{{ form.brand.label }}</td>#}
{#                <td>#}
{#                    {{ form.brand.errors }}#}
{#                    {{ form.brand }}#}
{#                </td>#}
{#                <td>{{ form.description.label }}</td>#}
{#                <td>{{ form.description }}</td>#}
{#            </tr>#}
{#            {{ form }}#}
{#            <tr>#}
{#                <td>#}
{#                    <button type="submit">Create</button>#}
{#                </td>#}
{#            </tr>#}
{#        </table>#}
{#    </form>#}

    <div class="content">
        <div class="row">
            <div class="col-6">
                <form method="post">{% csrf_token %}
                    {{ form.errors }}
                    <table>
                        {{ form }}
                        <tr>
                            <td>
                                <button type="submit">Create</button>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
            <div class="col-6">
                <ul>
                    {% for product in products %}
                    <li>
                        <a href="{% url 'product_detail' product.id %}"><b>{{ product.brand }}</b>: {{ product.number_plate }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

    </div>
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

templates/post_detail.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="/create_post/">Crate Post</a>
              </li>
            </ul>
          </div>
        </nav>
        <div class="container">
            <h1>{{ post.title }}</h1><br>
            <span>{{ post.created_at }}</span><br>
            {% for tag in post.tags.all %}
                <a href="/tag/{{tag.id}}">#{{ tag.name }}</a>,
            {% endfor %}
            <br>
            <br>
            <i><b>{{post.author.username}}</b></i>
            <p>
                {{ post.text }}
            </p>
        </div>
    </body>
</html>

templates/product_detail.html
{% extends 'base.html' %}
{% load custom_filters custom_tags static %}

{% block extra_header %}
    <title>My Django site!</title>
    <link rel="stylesheet" href="{% static "css/main.css" %}">
{% endblock %}

{% block content %}
    <table class="table">
        <tr>
            <td>Brand</td>
            <td>{{ product.brand }}</td>
        </tr>
        <tr>
            <td>Description</td>
            <td>{{ product.description }}</td>
        </tr>
        <tr>
            <td>Condition</td>
            <td>{{ product.get_condition_display }}</td>
        </tr>
        <tr>
            <td>Run km</td>
            <td>{{ product.run_km }}</td>
        </tr>
    </table>
    <table>
        {{ product_form }}
    </table>
{% endblock %}